# Generated by Django 5.0.6 on 2025-03-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('cgpa', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anandhu TS', max_length=100)),
                ('title', models.CharField(default='Junior Python Developer', max_length=200)),
                ('email', models.EmailField(default='anandhutsarun@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+918281350626', max_length=15)),
                ('linkedin', models.URLField(default='https://linkedin.com/in/anandhu-ts-bba348278')),
                ('location', models.CharField(default='Kollam, Kerala', max_length=100)),
                ('summary', models.TextField(default='A passionate fresher seeking a challenging position where I can apply my skills in programming languages, problem-solving abilities, and eagerness to learn. I am driven to contribute to the development of cutting-edge software solutions while continuously enhancing my expertise in the field. Motivated to work in dynamic environments that encourage growth and innovation.')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
